### ISSUE TITLE
quark's still legacy from being quarky

### ISSUE THREAD

**Issue by jprocket45** [jredfox/dungeontweeks#12]
Version: 1.2.5.1
Issue: not working with Quark Dungeons all it does when active is put pigs in the spawners 
Steps to reproduce: load up Quark  r1.5-130 with dungeontweeks look for a quark dungeon looks at spawners
CrashReport/Log: users always have logs even if it doesn't crash
ModPack/ModList:  Quark  r1.5-130 , AutoRegLib 1.3.20 ,  DungeonTweaks 1.2.5.1, EvilNotchLib 1.2.3-Snapshot 76
Forge 14.23.5.2768

side note- I thought i remember this working with Biomes O Plenty if not I am sorry for putting this with Biomes O Plenty ver  1.12.2.7.0.1.2402  installed it goes back to vanilla spawners will not add any other spawners.

**Comment by jredfox** [comment]
O I forgotten that quark had manual support is it crashing or spitting many exceptions in the console?

**Comment by jredfox** [comment]
biomes o plenty report as separate issue and without quark.

**Comment by jprocket45** [comment]
No Crash just pigs ive honestly loaded up at least 15 worlds to test it all i get is pigs in every spawner for quark dungeons.

**Comment by jprocket45** [comment]
if i remove the  dungeons mod and check it i see zombies and skeletons in the spawners with no issues.

**Comment by jredfox** [comment]
you didn't answer my question does the log throw a whole bunch of exceptions?

**Comment by jprocket45** [comment]
ummm im not sure I will try to get back to you on this if i figure out how to read the log since this is not on server im unfamiliar with reading the log my fault heh....  figured it out give me a few ill see if i can see anything on the log.

**Comment by jredfox** [comment]
keep log open when game fires or simply locate your log file latest

**Comment by jprocket45** [comment]
im not seeing anything but im sure i can get you  a copy of it.

**Comment by jredfox** [comment]
%appdata%/.minecraft/logs locate latest from there it's easier to organize them by date modified

**Comment by jprocket45** [comment]
[latest.log](https://github.com/jredfox/dungeontweeks/files/2466331/latest.log)

**Comment by jredfox** [comment]
create a new world nothing happened in that one

**Comment by jprocket45** [comment]
[latest.log](https://github.com/jredfox/dungeontweeks/files/2466401/latest.log)

**Comment by jredfox** [comment]
` java.lang.ClassNotFoundException: com.EvilNotch.dungeontweeks.main.Events.EventDungeon$Post` yes they are still supporting legacy version I am working on a new pull request for them this time with pre-populated like they intended it to be for their dungeons

**Comment by jprocket45** [comment]
ok hope to see a update soon then!

**Comment by jredfox** [comment]
it will be on quark's side not mine. Well If I use the new methods I just added now you will need to update both

**Comment by jprocket45** [comment]
ok is this something you will work on and forward to them or is this something i need to report? just making sure i understand it seems you are doing the work...

**Comment by jredfox** [comment]
They really don't care about my mod even though it provides an dungeon api that's superior to forge's so I will give them the new code. Plus it's faster

**Comment by jprocket45** [comment]
ok thanks! will speak with you soon again im sure with the other bug in biomes :)
