### ISSUE TITLE
BOP-ing Spawners?

### ISSUE THREAD

**Issue by jprocket45** [jredfox/dungeontweeks#13]
Version:1.2.5.1
Issue: When i load up with a Biomes O Plenty world it overrides the spawners it seems will only go back to what vanilla would spawn for instance in the mineshafts it just spawns the spiders in the spiderwebs if im not using biome o plenty it spawns random things i added in like slimes or guardians for instance.
Steps to reproduce:install Dungeontweeks and Biomes O Plenty change config to whatever you want even remove the zombies and skeletons and spiders it will still spawn them.
CrashReport/Log: no crash
ModPack/ModList:    Biomes O Plenty  1.312.2-7.0.1.2402  ,  DungeonTweaks 1.2.5.1    EvilNotchLib 1.2.3 Snapshot 76

hopefully I have explained this ok...

**Comment by jprocket45** [comment]
just going 1 step ahead of you here is a log lol 
[latest.log](https://github.com/jredfox/dungeontweeks/files/2466551/latest.log)

**Comment by jredfox** [comment]
unable to reproduce please specify steps in greater detail
