### ISSUE TITLE
Conflict with JC

### ISSUE THREAD

**Issue by brisingraerowing** [jredfox/dungeontweeks#17]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  evilnotchlib-transformer_fixes (EvilNotchLib-1.2.3-SNAPSHOt-78.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12/2/18 11:43 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.jurassicraft.client.sound.EntitySound.func_73660_a(EntitySound.java:33)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:235)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1857)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 651104784 bytes (620 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                             | Signature                                |
	|:------ |:------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft     | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJA | mcp           | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | evilnotchlib  | 1.2.3        | EvilNotchLib-1.2.3-SNAPSHOt-78.jar | None                                     |
	| UCHIJA | dungeontweaks | 1.2.5        | DungeonTweaks-1.2.5.2.jar          | None                                     |
	| UCHIJA | iitemrenderer | 1.2          | EvilNotchLib-1.2.3-SNAPSHOt-78.jar | None                                     |
	| UCHIJA | menulib       | 0.9          | EvilNotchLib-1.2.3-SNAPSHOt-78.jar | None                                     |
	| UCHIJA | llibrary      | 1.7.15       | llibrary-1.7.15-1.12.2.jar         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | jurassicraft  | 2.1.18       | JurassiCraft-1.12.2-2.1.18.jar     | None                                     |

	Loaded coremods (and transformers): 
evilnotchlib-transformer_fixes (EvilNotchLib-1.2.3-SNAPSHOt-78.jar)
  com.evilnotch.lib.asm.Transformer
  com.elix_x.itemrender.compat.asm.RenderTransformer
  com.evilnotch.menulib.asm.MenuLibTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

**Comment by jredfox** [comment]
thank you for your report I will look at it later. I am pretty sure however that the lib works with jc as I have tested that specific mod before. I don't know about dungeon tweaks

**Comment by jredfox** [comment]
I was able to get a crash but, not the same one you got. It appears to be an issue with llib & evil notch lib compat not jurassicraft

**Comment by jredfox** [comment]
unable to reproduce said bug. the crash report is invalid. the llib crashes by itself

**Comment by jredfox** [comment]
your issue is reproducible but, wasn't able to reproduce it as the lib had to be on an older forge and was crashing.

**Comment by jredfox** [comment]
I believe this is jc's side as they shouldn't be playing sounds like that? Every other mod seems to work except theirs
